### PR TITLE
feat(wiki): accept wiki names through open_wiki_index()

### PR DESCRIPTION
**Pull request by jqfeld**
allow specifying a name in `open_wiki_index`

### CODE REVIEW

**Review by serenevoid — CHANGES_REQUESTED** [review]
This looks like a good feature to have. Can you also update the README so that the users can know about this feature? 
Maybe update the config code's keymap part to take one wiki name from the list. With that addition, I think this PR will be ready to merge.

**Comment by jqfeld** [comment]
Do I understand correctly, that you would like to keep track of the `name` of the currently opened wiki in `require"kiwi".config`? Just to confirm, before I add the corresponding code :)

**Review by serenevoid — APPROVED** [review]
This is perfect. Thanks!

**Comment by serenevoid** [comment]
Personally, I feel like users can map different keymaps for different wiki folders. So, storing the last opened wiki inside config table won't be necessary. If we require this for later, we'll think about adding it then.

I really appreciate your help. Thanks for the PR!

**Pull request merged**
